#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: Energy system modelling workshop ESI                         # The title of the book. Will be placed in the left navbar.
author: Seth van Wieringen                        # The author of the book
copyright: "2024"                     # Copyright year to be placed in the footer
logo: logo.png                          # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/thesethtruth/esi-course-utwente  # Online location of your book
  path_to_book: esi-modelling-workshop  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true

launch_buttons:
  colab_url: "https://colab.research.google.com"

parse:
  myst_enable_extensions:
  - amsmath
  - dollarmath
  - linkify
  - colon_fence
  - substitution

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
